
import React, { useState, useMemo } from 'react';
import { useStore } from '../store/StoreContext';
import { PageHeader, DataTable, ModalBase, CustomSelect, ConfirmModal } from './Common';
import { Role, Permissions, ActionPermissions, UserAccess } from '../types';

const PermissionRow: React.FC<{
  label: string;
  permissions: ActionPermissions;
  onChange: (updates: Partial<ActionPermissions>) => void;
  disabled?: boolean;
}> = ({ label, permissions, onChange, disabled }) => {
  const toggle = (key: keyof ActionPermissions) => {
    if (disabled) return;
    onChange({ [key]: !permissions[key] });
  };

  const ActionToggle = ({ active, onClick, icon }: { active: boolean, onClick: () => void, icon: string }) => (
    <button 
      type="button"
      onClick={onClick}
      disabled={disabled}
      className={`w-10 h-10 rounded-sm border flex items-center justify-center transition-all ${active ? 'bg-vista-accent/20 border-vista-accent text-vista-accent' : 'bg-neutral-50 dark:bg-neutral-800 border-neutral-200 dark:border-neutral-700 text-neutral-400 opacity-40'}`}
      title={icon}
    >
      <span className="text-[10px] font-bold uppercase">{icon[0]}</span>
    </button>
  );

  return (
    <div className="flex items-center justify-between p-4 bg-white dark:bg-neutral-900 border border-neutral-100 dark:border-neutral-800 rounded-sm">
      <div>
        <span className="text-xs font-bold text-neutral-900 dark:text-vista-text uppercase tracking-widest">{label}</span>
      </div>
      <div className="flex gap-2">
        <ActionToggle active={permissions.read} onClick={() => toggle('read')} icon="Read" />
        <ActionToggle active={permissions.create} onClick={() => toggle('create')} icon="Create" />
        <ActionToggle active={permissions.update} onClick={() => toggle('update')} icon="Update" />
        <ActionToggle active={permissions.delete} onClick={() => toggle('delete')} icon="Delete" />
      </div>
    </div>
  );
};

export const AccessView: React.FC = () => {
  const { roles, userAccessList, addRole, updateRole, removeRole, updateUserAccess } = useStore();
  const [activeTab, setActiveTab] = useState<'users' | 'roles'>('users');
  
  // Modals
  const [editingUser, setEditingUser] = useState<UserAccess | null>(null);
  const [editingRole, setEditingRole] = useState<Role | null>(null);
  const [isAddingRole, setIsAddingRole] = useState(false);
  const [roleToDelete, setRoleToDelete] = useState<Role | null>(null);

  // New Role State
  const [newRoleName, setNewRoleName] = useState('');
  const [newRolePermissions, setNewRolePermissions] = useState<Permissions>(() => JSON.parse(JSON.stringify(DEFAULT_PERMISSIONS)));

  const handleUpdateUserPermissions = (resource: keyof Permissions, updates: Partial<ActionPermissions>) => {
    if (!editingUser) return;
    const currentCustom = editingUser.customPermissions || {};
    const basePermissions = roles.find(r => r.id === editingUser.roleId)?.permissions;
    if (!basePermissions) return;

    const newCustom = {
      ...currentCustom,
      [resource]: {
        ...(currentCustom[resource] || basePermissions[resource]),
        ...updates
      }
    };
    setEditingUser({ ...editingUser, customPermissions: newCustom });
  };

  const handleSaveUser = () => {
    if (!editingUser) return;
    updateUserAccess(editingUser.userId, editingUser);
    setEditingUser(null);
  };

  const handleUpdateRolePermissions = (resource: keyof Permissions, updates: Partial<ActionPermissions>) => {
    if (!editingRole) return;
    const newPermissions = {
      ...editingRole.permissions,
      [resource]: {
        ...editingRole.permissions[resource],
        ...updates
      }
    };
    setEditingRole({ ...editingRole, permissions: newPermissions });
  };

  const handleSaveRole = () => {
    if (!editingRole) return;
    updateRole(editingRole.id, editingRole);
    setEditingRole(null);
  };

  const handleCreateRole = () => {
    if (!newRoleName) return;
    addRole({
      id: '', // Generated by DB
      name: newRoleName,
      permissions: newRolePermissions
    });
    setIsAddingRole(false);
    setNewRoleName('');
    setNewRolePermissions(JSON.parse(JSON.stringify(DEFAULT_PERMISSIONS)));
  };

  return (
    <div className="p-4 md:p-8 max-w-6xl mx-auto space-y-8 animate-fade-in">
      <PageHeader 
        title="Access Management" 
        subtitle="Control user permissions and role definitions."
        actions={
          activeTab === 'roles' && (
            <button 
              onClick={() => setIsAddingRole(true)}
              className="px-6 py-2 bg-neutral-900 dark:bg-vista-accent text-white dark:text-neutral-900 text-[10px] font-bold uppercase tracking-widest rounded-sm shadow-xl"
            >
              + Create Role
            </button>
          )
        }
      />

      <div className="flex gap-8 border-b border-neutral-100 dark:border-neutral-800">
        <button 
          onClick={() => setActiveTab('users')}
          className={`pb-4 text-[10px] font-bold uppercase tracking-widest transition-all ${activeTab === 'users' ? 'text-vista-accent border-b-2 border-vista-accent' : 'text-neutral-400 hover:text-neutral-600'}`}
        >
          Users
        </button>
        <button 
          onClick={() => setActiveTab('roles')}
          className={`pb-4 text-[10px] font-bold uppercase tracking-widest transition-all ${activeTab === 'roles' ? 'text-vista-accent border-b-2 border-vista-accent' : 'text-neutral-400 hover:text-neutral-600'}`}
        >
          Roles
        </button>
      </div>

      {activeTab === 'users' ? (
        <DataTable<UserAccess>
          data={userAccessList}
          columns={[
            { header: 'User Email', isSticky: true, render: u => u.email },
            { header: 'Assigned Role', render: u => roles.find(r => r.id === u.roleId || r.name === u.roleId)?.name || 'None' },
            { header: 'Status', render: u => <span className="text-[10px] text-emerald-500 font-bold uppercase">Authorized</span> },
            { header: 'Actions', align: 'right', render: u => (
              <button 
                onClick={() => setEditingUser(u)}
                className="text-xs font-bold text-neutral-400 hover:text-vista-accent uppercase tracking-widest underline decoration-transparent hover:decoration-vista-accent underline-offset-4 transition-all"
              >
                Manage
              </button>
            )}
          ]}
        />
      ) : (
        <DataTable<Role>
          data={roles}
          columns={[
            { header: 'Role Name', isSticky: true, render: r => r.name },
            { header: 'Users Count', render: r => userAccessList.filter(u => u.roleId === r.id || u.roleId === r.name).length },
            { header: 'Actions', align: 'right', render: r => (
              <div className="flex gap-4 justify-end">
                <button 
                  onClick={() => setEditingRole(r)}
                  className="text-xs font-bold text-neutral-400 hover:text-vista-accent uppercase tracking-widest underline decoration-transparent hover:decoration-vista-accent underline-offset-4 transition-all"
                >
                  Edit
                </button>
                {r.name !== 'Owner' && (
                  <button 
                    onClick={() => setRoleToDelete(r)}
                    className="text-xs font-bold text-neutral-400 hover:text-red-500 uppercase tracking-widest"
                  >
                    Delete
                  </button>
                )}
              </div>
            )}
          ]}
        />
      )}

      {/* Role Creation Modal */}
      {isAddingRole && (
        <ModalBase isOpen={isAddingRole} onClose={() => setIsAddingRole(false)} title="Create New Role" footer={
          <>
            <button onClick={() => setIsAddingRole(false)} className="px-4 py-2 text-neutral-500 text-xs font-bold uppercase">Cancel</button>
            <button onClick={handleCreateRole} className="px-8 py-2 bg-neutral-900 dark:bg-vista-accent text-white dark:text-neutral-900 text-xs font-bold uppercase rounded-sm shadow-xl">Create Role</button>
          </>
        }>
          <div className="space-y-6">
            <div>
              <label className="block text-[10px] font-bold text-neutral-400 uppercase tracking-widest mb-2">Role Name</label>
              <input 
                type="text"
                className="w-full border border-neutral-300 dark:border-neutral-700 rounded-sm p-3 text-sm bg-transparent outline-none focus:border-vista-accent text-neutral-900 dark:text-vista-text"
                placeholder="e.g. Inventory Manager"
                value={newRoleName}
                onChange={(e) => setNewRoleName(e.target.value)}
              />
            </div>

            <div className="space-y-3">
               {['products', 'ingredients', 'packaging', 'sales', 'access'].map((resource) => {
                  const r = resource as keyof Permissions;
                  return (
                    <PermissionRow 
                      key={r}
                      label={resource}
                      permissions={newRolePermissions[r]}
                      onChange={(updates) => setNewRolePermissions(prev => ({
                        ...prev,
                        [r]: { ...prev[r], ...updates }
                      }))}
                    />
                  );
                })}
            </div>
          </div>
        </ModalBase>
      )}

      {/* User Editing Modal */}
      {editingUser && (
        <ModalBase isOpen={!!editingUser} onClose={() => setEditingUser(null)} title={`Access: ${editingUser.email}`} footer={
          <>
            <button onClick={() => setEditingUser(null)} className="px-4 py-2 text-neutral-500 text-xs font-bold uppercase">Cancel</button>
            <button onClick={handleSaveUser} className="px-8 py-2 bg-neutral-900 dark:bg-vista-accent text-white dark:text-neutral-900 text-xs font-bold uppercase rounded-sm shadow-xl">Apply Changes</button>
          </>
        }>
          <div className="space-y-6">
            <div>
              <label className="block text-[10px] font-bold text-neutral-400 uppercase tracking-widest mb-2">Base Role</label>
              <CustomSelect 
                options={roles.map(r => ({ value: r.id || r.name, label: r.name }))}
                value={editingUser.roleId}
                onChange={(val) => setEditingUser({ ...editingUser, roleId: val, customPermissions: undefined })}
              />
            </div>

            <div className="space-y-2">
              <label className="block text-[10px] font-bold text-neutral-400 uppercase tracking-widest">Fine-tuned Permissions</label>
              <div className="space-y-3">
                {['products', 'ingredients', 'packaging', 'sales', 'access'].map((resource) => {
                  const r = resource as keyof Permissions;
                  const base = roles.find(role => role.id === editingUser.roleId || role.name === editingUser.roleId)?.permissions[r] || DEFAULT_PERMISSIONS[r];
                  const current = editingUser.customPermissions?.[r] || base;
                  return (
                    <PermissionRow 
                      key={r}
                      label={resource}
                      permissions={current}
                      onChange={(updates) => handleUpdateUserPermissions(r, updates)}
                      disabled={editingUser.email === 'safwatkamel6000@gmail.com'}
                    />
                  );
                })}
              </div>
            </div>
          </div>
        </ModalBase>
      )}

      {/* Role Editing Modal */}
      {editingRole && (
        <ModalBase isOpen={!!editingRole} onClose={() => setEditingRole(null)} title={`Edit Role: ${editingRole.name}`} footer={
          <>
            <button onClick={() => setEditingRole(null)} className="px-4 py-2 text-neutral-500 text-xs font-bold uppercase">Cancel</button>
            <button onClick={handleSaveRole} className="px-8 py-2 bg-neutral-900 dark:bg-vista-accent text-white dark:text-neutral-900 text-xs font-bold uppercase rounded-sm shadow-xl">Save Role</button>
          </>
        }>
          <div className="space-y-6">
            <div>
              <label className="block text-[10px] font-bold text-neutral-400 uppercase tracking-widest mb-2">Role Name</label>
              <input 
                type="text"
                className="w-full border border-neutral-300 dark:border-neutral-700 rounded-sm p-3 text-sm bg-transparent outline-none focus:border-vista-accent text-neutral-900 dark:text-vista-text"
                value={editingRole.name}
                onChange={(e) => setEditingRole({ ...editingRole, name: e.target.value })}
                disabled={editingRole.name === 'Owner'}
              />
            </div>

            <div className="space-y-3">
               {['products', 'ingredients', 'packaging', 'sales', 'access'].map((resource) => {
                  const r = resource as keyof Permissions;
                  return (
                    <PermissionRow 
                      key={r}
                      label={resource}
                      permissions={editingRole.permissions[r]}
                      onChange={(updates) => handleUpdateRolePermissions(r, updates)}
                      disabled={editingRole.name === 'Owner'}
                    />
                  );
                })}
            </div>
          </div>
        </ModalBase>
      )}

      {/* Deletion Confirmation */}
      <ConfirmModal 
        isOpen={!!roleToDelete}
        title="Delete Role"
        message={`Are you sure you want to delete the "${roleToDelete?.name}" role? Users assigned to this role may lose access permissions.`}
        confirmText="Delete Role"
        isDestructive={true}
        onConfirm={() => {
          if (roleToDelete) removeRole(roleToDelete.id);
          setRoleToDelete(null);
        }}
        onCancel={() => setRoleToDelete(null)}
      />
    </div>
  );
};

const DEFAULT_PERMISSIONS: Permissions = {
  products: { read: true, create: false, update: false, delete: false },
  ingredients: { read: true, create: false, update: false, delete: false },
  packaging: { read: true, create: false, update: false, delete: false },
  sales: { read: true, create: false, update: false, delete: false },
  access: { read: false, create: false, update: false, delete: false },
};
